name: Deploy demo
on:
    workflow_dispatch:
    push:
        paths: ["./**"]
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: demo
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: wasm32-unknown-unknown
                  override: true
            - name: Install Cargo BInstall
              uses: cargo-bins/cargo-binstall@main
            - name: Install Cargo Leptos
              run: cargo binstall cargo-leptos -y
            - name: Build
              run: | 
                  cargo leptos build --release
            - name: Deploy
              uses: amondnet/vercel-action@v20
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  vercel-args: "--prod"
                  working-directory: ./target
                  vercel-project-name: leptail